name: json_text_field
description: "Flutter widget that automatically formats text in a JSON format."
version: 1.1.0
homepage: https://github.com/antonioCaballero17/json_text_field

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  extended_text_field: ^16.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
